<form action="">
    <h3>Pagina de Login </h3>
    <label for="first">Nome de usuário:</label> <br>
<input type="text" id="first" name="first" 
    placeholder="Digite seu nome de usuário" obrigatório> <br>

<label for="password">Senha:</label><br>
<input type="password" id="password" name="password" 
    placeholder="Digite sua senha" obrigatório><br>

 
  <button type="submit" class="btn btn-primary">Enviar</button>

</form>


