<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <!-- Link para homepage (rota raiz) -->
        <a class="navbar-brand" href="/">Classificados</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="d-flex justify-content-end collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <!-- Link para página de anunciantes -->
                <li class="nav-item">
                    <a class="nav-link" href="/anunciantes" role="button">
                        Anunciantes
                    </a>
                </li>
                
                <!-- Link para página de anúncios -->
                <li class="nav-item">
                    <a class="nav-link" href="/anuncios" role="button">
                        Anúncios
                    </a>
                </li>
                
                <!-- Link para página de Categorias -->
                <li class="nav-item">
                    <a class="nav-link" href="/categorias" role="button">
                        Categorias
                    </a>
                </li>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Opções ≡
                    </a>
                    <ul class="dropdown-menu">
                        <!-- Link para perfil do usuário -->
                        <li><a class="dropdown-item" href="/usuario/perfil">Perfil</a></li>
                        <li><hr class="dropdown-divider"></li>
                        
                        <!-- Link para logout -->
                        <li><a class="dropdown-item" href="/logout">Sair</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>