<section>
    <h2>Listar Anuncio</h2>

    <hr>

<div>
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Descrição</th>
                    <th>Status</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Carro 2020</td>
                    <td>Carro ano 2020 da Raimundinha zero bala </td>
                    <td>Rascunho</td>
                    <td>
                        <divrole='group' aria-label='Basic mixed styles example'>
                            <button type='button'>Editar</button>
                            <button type='button'>Excluir</button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    
</section>