<section class="card card-body mt-5">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>Listar Anuncio</h2>
        <a href="/anuncios/adicionar" class="btn btn-warning mt-1">
            Cadastrar Anúncio
        </a>
    </div>
    <hr>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <tr>
                    <th>Title</th>
                    <th>Descrição</th>
                    <th>Status</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php

                    foreach ($anuncios as $cada) {
                        $id = $cada->getId();
                        $json = htmlspecialchars(json_encode($cada), ENT_QUOTES, 'UTF-8');

                        echo "
                            <tr>
                                <td>{$cada->getTitle()}</td>
                                <td>{$cada->getDescription()}</td>
                                <td>{$cada->getStatus()->value}</td>
                                <td class='text-center'>
                                    <div class='btn-group' role='group' aria-label='Basic mixed styles example'>
                                        <button type='button' class='btn btn-warning'>Editar</button>
                                        <button type='button' class='btn btn-danger'>Excluir</button>
                                    </div>
                                </td>
                            </tr>
                        ";
                    }
                ?> 
            </tbody>
        </table>
    </div>
</section>