<section class="card card-body mt-5">
<form>
<div class="row">
    <div class="col">
        <img src="/assets/images/add-advertisement.svg" width="80%" alt=""
    </div>
        
    <label for="exampleInputEmail1" class="form-label">Nome</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text"></div>
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Endereço de email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text"></div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Senha</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Checar</label>
  </div>
  <button type="submit" class="btn btn-primary">Enviar</button>
    <label class="form-check-label" for="exampleCheck1">Confira me</label>
  </div>
</div>
  
</form>
</section>