<section class="card card-body mt-5">
  <h2>Cadastro de anunciante</h2>

  <hr>

  <div class="row">
    <div class="col">
      <img src="/assets/images/add-advertisement.svg" width="80%" alt="">
    </div>
    <div class="col">
    <div class="form-group">
    <label for="exampleInputEmail1">Nome</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Digite aqui o seu nome">
    <small id="emailHelp" class="form-text text-muted">O sistema segue as diretrizes da LGPT</small>
  </div>
     <div class="form-group">
    <label for="exampleInputEmail1">Endereço de email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Insira o seu email aqui">
    <small id="emailHelp" class="form-text text-muted">Nunca compartilharemos seu e-mail com mais ninguém.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Senha</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Senha">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Conferir</label>
  </div>
  <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
  </div>
</section>